[package]
name = "bm-example-rust-sdk-embedded"
version = "0.1.0"
edition = "2021"
publish = false

[workspace]

[features]
default = ["desktop-macos"]
desktop-macos = ["bm-sdk/profile-desktop-macos-embedded-sdk"]
desktop-windows = ["bm-sdk/profile-desktop-windows-embedded-sdk"]
desktop-linux = ["bm-sdk/profile-desktop-linux-embedded-sdk"]

[dependencies]
bm-sdk = { path = "../../crates/sdk", default-features = false }
