[package]
name = "bm-example-linux-device"
version = "0.1.0"
edition = "2021"
publish = false

[workspace]

[dependencies]
bm-adapter = { path = "../../crates/adapter", features = ["profile-linux-device-standalone-memory"] }
bm-entry = { path = "../../crates/entry", features = ["profile-linux-device-standalone-memory"] }
bm-sdk = { path = "../../crates/sdk", features = ["profile-linux-device-standalone-memory"] }
