[package]
name = "bm-example-server-runtime"
version = "0.1.0"
edition = "2021"
publish = false

[workspace]

[dependencies]
bm-entry = { path = "../../crates/entry", features = ["profile-server-linux-dev-full"] }
bm-http = { path = "../../crates/http", features = ["profile-server-linux-dev-full", "server-std"] }
bm-sdk = { path = "../../crates/sdk", features = ["profile-server-linux-dev-full"] }
